### ISSUE TITLE
error in cloning fano-api

### ISSUE THREAD

**Issue by nomorelogic** [fanoframework/fano#2]
hi
first, thank for sharing this project :)
this issue is related to repo fano-api

In your read-me I can read a statement to clone fano-api repository
`git clone git@github.com:fanoframework/fano-api.git --recursive`

but this is the response

```
Cloning in 'fano-api'...
The authenticity of host 'github.com (140.82.118.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.118.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Unable to read remote repository.

Make sure you have the correct access privileges
and that the repository exists.

```
I solved using this statement
`git clone https://github.com/fanoframework/fano-api.git --recursive`

I tried `git submodule update --init` but submodule fano is impossible to clone to me (again error is: Make sure you have the correct access privileges and that the repository exists.).
So I downloaded by hand fano repo into subfolder. 

Can you fix this step in doc please?

**Comment by zamronypj** [comment]
This is issue about ssh, not directly to fano-api repository. 

If you want to use git clone with ssh, you need to setup public key as this is ssh protocol requirement. ssh does not care if it is private repository or public repository. 

However I update fano-api repository and edit readme to avoid any confusion.
