### ISSUE TITLE
fanocli refuses creating controller with no git in a project

### ISSUE THREAD

**Issue by ooptimum** [fanoframework/fano#21]
fanocli doesn't create controllers and issues the following message:
_Current directory was not generated by Fano CLI. Try create project first, for example with --project-scgi or --project-fcgi.
Run with --help option to view available task._
if run within project's directory, which was created with --no-git flag

**Comment by zamronypj** [comment]
@ooptimum Thank you for reporting this issue. I will look into it as soon as I have time.

**Comment by zamronypj** [comment]
Fixed in fanoframework/fano-cli@f3c43ac
