### ISSUE TITLE
installation broken for linux debian(Kali)

### ISSUE THREAD

**Issue by lawrenceamer** [fanoframework/fano#30]
Hi trying to have a look into fano but unfortunately not able to install fano-cli due to some missing units on the src installation code, not sure where the error is located, as i already have FPC +3 installed + lazarus-IDE 

```
Compiling ./src/Tasks/Implementations/Minifier/DirFileMinifierTaskImpl.pas
Writing Resource String Table file: DirFileMinifierTaskImpl.rsj
Compiling ./src/Libs/Minifier/Implementations/JsMinifierImpl.pas
Compiling ./src/Libs/Minifier/Contracts/MinifierIntf.pas
JsMinifierImpl.pas(18,5) Fatal: Can't find unit jsminifier used by JsMinifierImpl
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode

```

**Comment by zamronypj** [comment]
Close this issue as it related to Fano CLI and duplicates https://github.com/fanoframework/fano-cli/issues/10
